theme: jekyll-theme-cayman

webrick:
  headers:
    My-Header: My-Value
    My-Other-Header: My-Other-Value

defaults:
  -
    scope:
      path: "" # 一个空的字符串代表项目中所有的文件
      type: "posts" # 以前的 `post`， 在 Jekyll 2.2 里。
    values:
      layout: "default"